name: Setup
description: Sets up Node.js, yarn and caches `node_modules`

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
      shell: sh
