name: Setup
description: Sets up Node.js, yarn and caches `node_modules`

inputs:
  install-dependencies:
    description: When 'true', dependencies will be installed
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      run: yarn install
      shell: sh
