language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - yarn
before_deploy:
  - yarn build
deploy:
  provider: pages
  keep-history: true
  skip_cleanup: true
  committer-from-gh: true
  github_token: $GITHUB_TOKEN
  verbose: true
  local_dir: /dist
  target-branch: master
  on:
    branch: development
script:
  - yarn danger-ci
  - yarn build
  - npx bundlesize
after_success:
  - npx semantic-release