language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - yarn
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: /dist
  github_token: $GH_TOKEN
  on:
    branch: master
script:
  - yarn danger-ci
  - yarn build
  - npx bundlesize
after_success:
  - npx semantic-release