const light = {
  'is-contrast': '0',
  'is-dark': '0',
  background: '#f8f9fa',
  'background-opaque': 'rgba(255, 255, 255, 0.5)',
  backdrop: 'rgba(0, 0, 0, 0.5)',
  'menu-background': 'transparent',
  'menu-background-fallback': 'rgba(255, 255, 255, 0.75)',
  text: '#292e31',
  'testimonial-card-background': '#f8f9fa',
  'testimonial-card-border': '#d3d3d3',
  'testimonial-card-text': '#292e31',
  shadow: 'rgba(0, 0, 0, 0.2)',
  'table-cell-background': 'rgba(0, 0, 0, 0.02)',
  'scrollbar-track-color': '#838383',
  'accent-color': 'auto',
};

const dark = {
  'is-contrast': '0',
  'is-dark': '1',
  background: '#0e141b',
  'background-opaque': 'rgba(0, 0, 0, 0.2)',
  backdrop: 'rgba(255, 255, 255, 0.05)',
  'menu-background': 'transparent',
  'menu-background-fallback': 'rgba(0, 0, 0, 0.75)',
  text: '#ffffff',
  'testimonial-card-background': '#282828',
  'testimonial-card-border': '#3e3e3e',
  'testimonial-card-text': '#f3f3f3',
  shadow: 'rgba(100, 100, 100, 0.2)',
  'table-cell-background': 'rgba(255, 255, 255, 0.02)',
  'scrollbar-track-color': '#424242',
  'accent-color': 'auto',
};

export const contrast = {
  name: 'Contrast',
  light: {
    'is-contrast': '1',
    'is-dark': '0',
    background: 'white',
    'background-opaque': 'rgba(255, 255, 255, 0.5)',
    backdrop: 'rgba(0, 0, 0, 0.8)',
    'menu-background': 'white',
    'menu-background-fallback': 'white',
    text: 'black',
    'testimonial-card-background': 'white',
    'testimonial-card-border': 'black',
    'testimonial-card-text': 'black',
    shadow: 'transparent',
    'table-cell-background': 'rgba(0, 0, 0, 0.01)',
    'scrollbar-track-color': '#838383',
    //
    'primary-bright': '#383838',
    'primary-dark': 'black',
    'secondary-bright': '#525252',
    'secondary-dark': '#282828',
    'highlight-accent-rgb': '255, 255, 255',
    'highlight-rgb': '0, 0, 0',
    'accent-color': 'white',
  },
  dark: {
    'is-contrast': '1',
    'is-dark': '1',
    background: 'black',
    'background-opaque': 'rgba(0, 0, 0, 0.2)',
    backdrop: 'rgba(255, 255, 255, 0.5)',
    'menu-background': 'black',
    'menu-background-fallback': 'black',
    text: 'white',
    'testimonial-card-background': 'black',
    'testimonial-card-border': 'white',
    'testimonial-card-text': 'white',
    shadow: 'transparent',
    'table-cell-background': 'rgba(255, 255, 255, 0.01)',
    'scrollbar-track-color': '#424242',
    //
    'primary-bright': 'white',
    'primary-dark': '#bfbfbf',
    'secondary-bright': '#ededed',
    'secondary-dark': '#b3b3b3',
    'highlight-rgb': '255, 255, 255',
    'highlight-accent-rgb': '0, 0, 0',
    'accent-color': 'black',
  },
};

const themes = [
  {
    name: 'Orange',
    light: {
      ...light,
      'primary-bright': '#ee0979',
      'primary-dark': '#77043c',
      'secondary-bright': '#ff6a00',
      'secondary-dark': '#7f3401',
      'highlight-rgb': '238, 9, 121',
      'highlight-accent-rgb': '255, 106, 0',
      'accent-color': '#ee0979',
    },
    dark: {
      ...dark,
      'primary-bright': '#ee0979',
      'primary-dark': '#77043c',
      'secondary-bright': '#ff6a00',
      'secondary-dark': '#7f3401',
      'highlight-rgb': '238, 9, 121',
      'highlight-accent-rgb': '255, 106, 0',
      'accent-color': '#ee0979',
    },
  },
  {
    name: 'Cyan',
    light: {
      ...light,
      'primary-bright': '#4ca1af',
      'primary-dark': '#265057',
      'secondary-bright': '#c4e0e5',
      'secondary-dark': '#606f72',
      'highlight-rgb': '76, 161, 175',
      'highlight-accent-rgb': '73, 134, 145',
      'accent-color': '#4ca1af',
    },
    dark: {
      ...dark,
      'primary-bright': '#4ca1af',
      'primary-dark': '#265057',
      'secondary-bright': '#c4e0e5',
      'secondary-dark': '#606f72',
      'highlight-rgb': '76, 161, 175',
      'highlight-accent-rgb': '196, 224, 229',
      'accent-color': '#4ca1af',
    },
  },
  {
    name: 'Vice',
    light: {
      ...light,
      'primary-bright': '#ec6ead',
      'primary-dark': '#763756',
      'secondary-bright': '#3494e6',
      'secondary-dark': '#1d4972',
      'highlight-rgb': '236, 110, 173',
      'highlight-accent-rgb': '52, 148, 230',
      'accent-color': '#ec6ead',
    },
    dark: {
      ...dark,
      'primary-bright': '#ec6ead',
      'primary-dark': '#763756',
      'secondary-bright': '#3494e6',
      'secondary-dark': '#1d4972',
      'highlight-rgb': '236, 110, 173',
      'highlight-accent-rgb': '52, 148, 230',
      'accent-color': '#ec6ead',
    },
  },
  {
    name: 'Purple',
    light: {
      ...light,
      'primary-bright': '#7f00ff',
      'primary-dark': '#3f007f',
      'secondary-bright': '#e100ff',
      'secondary-dark': '#6f007f',
      'highlight-rgb': '127, 0, 255',
      'highlight-accent-rgb': '225, 0, 255',
      'accent-color': '#7f00ff',
    },
    dark: {
      ...dark,
      'primary-bright': '#7f00ff',
      'primary-dark': '#3f007f',
      'secondary-bright': '#e100ff',
      'secondary-dark': '#6f007f',
      'highlight-rgb': '72, 0, 145',
      'highlight-accent-rgb': '225, 0, 255',
      'accent-color': '#7f00ff',
    },
  },
];

export type Theme = typeof themes[number];

export default themes;
