name: Release

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Project setup
        uses: ./.github/actions/setup
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_CONTACT_ENDPOINT: ${{ vars.NEXT_PUBLIC_CONTACT_ENDPOINT }}
          NEXT_PUBLIC_FULLSTORY_ORG_ID: ${{ vars.NEXT_PUBLIC_FULLSTORY_ORG_ID }}
        run: yarn build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  semantic_release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Project setup
        uses: ./.github/actions/setup
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_CONTACT_ENDPOINT: ${{ vars.NEXT_PUBLIC_CONTACT_ENDPOINT }}
          NEXT_PUBLIC_FULLSTORY_ORG_ID: ${{ vars.NEXT_PUBLIC_FULLSTORY_ORG_ID }}
        run: npx semantic-release
